/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as FindingRouteImport } from './routes/finding'
import { Route as MeRouteImport } from './routes/me'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TripRouteImport } from './routes/trip'
import { Route as WalletRouteImport } from './routes/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingRoute = FindingRouteImport.update({
  id: '/finding',
  path: '/finding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/finding': typeof FindingRoute
  '/me': typeof MeRoute
  '/orders': typeof OrdersRoute
  '/promo': typeof PromoRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/trip': typeof TripRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/finding': typeof FindingRoute
  '/me': typeof MeRoute
  '/orders': typeof OrdersRoute
  '/promo': typeof PromoRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/trip': typeof TripRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/finding': typeof FindingRoute
  '/me': typeof MeRoute
  '/orders': typeof OrdersRoute
  '/promo': typeof PromoRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/trip': typeof TripRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/finding'
    | '/me'
    | '/orders'
    | '/promo'
    | '/support'
    | '/tracking'
    | '/trip'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/finding'
    | '/me'
    | '/orders'
    | '/promo'
    | '/support'
    | '/tracking'
    | '/trip'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/finding'
    | '/me'
    | '/orders'
    | '/promo'
    | '/support'
    | '/tracking'
    | '/trip'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  FindingRoute: typeof FindingRoute
  MeRoute: typeof MeRoute
  OrdersRoute: typeof OrdersRoute
  PromoRoute: typeof PromoRoute
  SupportRoute: typeof SupportRoute
  TrackingRoute: typeof TrackingRoute
  TripRoute: typeof TripRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finding': {
      id: '/finding'
      path: '/finding'
      fullPath: '/finding'
      preLoaderRoute: typeof FindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  FindingRoute: FindingRoute,
  MeRoute: MeRoute,
  OrdersRoute: OrdersRoute,
  PromoRoute: PromoRoute,
  SupportRoute: SupportRoute,
  TrackingRoute: TrackingRoute,
  TripRoute: TripRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
